### PR TITLE
Add .gitignore file

### PR DESCRIPTION
**Pull request by gustavocardosomoreira**
*** Note: I urge you, if acceptable, to accept this PR using a *rebase* instead of a merge; that way we won't pollute git history with a merge of a tiny branch, and the commits will be incorporated linearly into master.

**Contents of .gitignore file**
* The first part of the file (lines 1-140) is to be used for [Python projects](https://github.com/github/gitignore/blob/master/Python.gitignore), from GitHub's own repo;
* The second part of the file (Line 140 onwards) is supplied by Toptal for [PyCharm](https://www.toptal.com/developers/gitignore/api/pycharm+all) projects, which is the IDE I use;

### CODE REVIEW

**Comment by amoe** [comment]
Hi Gustavo, thanks for the PR.  I'd rather not merge this as-is.  I only want to have rules in `.gitignore` that are actually used by the project or IDEs of people who work on it.  Which of these rules do you use directly?

Obviously stuff like `__pycache__` is fine.  I also use PyCharm sometimes, but I'd prefer a minimal set of PyCharm-specific rules.

**Comment by gustavocardosomoreira** [comment]
Dear Mr Banks, greetings. I only need these three rules:
`__pychache__/`
`.pytest_cache/`
`venv/`
Should I push a new commit with the minimal file?

**Comment by amoe** [comment]
> Dear Mr Banks, greetings. I only need these three rules:
> `__pychache__/`
> `.pytest_cache/`
> `venv/`
> Should I push a new commit with the minimal file?

Yep, that would work for me.  :+1:

**Comment by amoe** [comment]
LGTM!

**Pull request merged**
